version: "3.7"
services:
  sf-nginx:
    build: ./docker/development/nginx
    container_name: sf-nginx
    ports:
      - "80:80"
    volumes:
      - ./app/public:/usr/src/app/public:ro
      - ./logs/nginx:/var/log/nginx
    links:
      - sf-php-fpm
  sf-php-fpm:
    build: ./docker/development/php/7.3/fpm
    container_name: sf-php-fpm
    volumes:
      - ./app:/usr/src/app:rw
      - ./logs/symfony:/usr/src/app/var/log
    links:
      - sf-db
      - sf-redis
  sf-php-cli:
    build: ./docker/development/php/7.3/cli
    container_name: sf-php-cli
    volumes:
      - ./app:/usr/src/app:rw
      - ./logs/symfony:/usr/src/app/var/log
      - composer:/root/.composer/cache
    # user: "${UID-www-data}:${GID-www-data}"
    links:
      - sf-db
      - sf-redis
    ports:
      - "9000:9001"
    tty: true
  sf-node:
    image: node:12.7-alpine
    container_name: sf-node
    volumes:
      - ./app:/usr/src/app:rw
      - ./logs/symfony:/usr/src/app/var/log
    working_dir: /usr/src/app
    tty: true
  sf-db:
    image: postgres:11.2-alpine
    container_name: sf-db
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfonist}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-blog_db}
    ports:
      - "54321:5432"
  sf-adminer:
    image: adminer
    container_name: sf-adminer
    links:
      - sf-db
    restart: always
    ports:
      - "2000:8080"
  sf-redis:
    image: redis:5-alpine
    container_name: sf-redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    command:
      - 'redis-server'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--requirepass secret'
volumes:
  db-data:
  redis:
  composer:
